roboptim::detail Namespace Reference
roboptim::detail Namespace Reference
Classes
class Tnlp
Typedefs
typedef Ipopt::Index Index
typedef Ipopt::Number Number
Functions
template<typename T , typename F >
void IpoptCheckGradient (const F &, unsigned, Eigen::Map< const Function::vector_t > &, int, T &) throw ()
void jacobianFromGradients (DerivableFunction::matrix_t &jac, const IpoptSolver::problem_t::constraints_t &c, const DerivableFunction::vector_t &x)
ROBOPTIM_CORE_IPOPT_PLUGIN_CHECK_GRADIENT.
template<typename T >
Function::size_type computeConstraintsOutputSize (const T &solver)
Typedef Documentation
typedef Ipopt::Index roboptim::detail::Index
typedef Ipopt::Number roboptim::detail::Number
Function Documentation
template<typename T > Function::size_type roboptim::detail::computeConstraintsOutputSize (const T & solver)
References roboptim::IpoptSolverCommon< Solver< DifferentiableFunction, boost::mpl::vector< LinearFunction, DifferentiableFunction > > >::LINEAR.
Referenced by roboptim::detail::Tnlp< T >::constraintsOutputSize().
template<typename T , typename F > void roboptim::detail::IpoptCheckGradient (const F & , unsigned , Eigen::Map< const Function::vector_t > & , int , T &) throw ()
Referenced by roboptim::detail::Tnlp< T >::eval_grad_f(), and roboptim::detail::Tnlp< T >::eval_jac_g().
void roboptim::detail::jacobianFromGradients (DerivableFunction::matrix_t & jac, const IpoptSolver::problem_t::constraints_t & c, const DerivableFunction::vector_t & x)
ROBOPTIM_CORE_IPOPT_PLUGIN_CHECK_GRADIENT.