roboptim::detail::Tnlp< T > Class Template Reference
roboptim::detail::Tnlp< T > Class Template Reference
#include <tnlp.hh>
Public Types
typedef T solver_t
Public Member Functions
Tnlp (const typename solver_t::problem_t &pb, solver_t &solver) throw ()
Function::size_type constraintsOutputSize ()
virtual bool get_nlp_info (Index &n, Index &m, Index &nnz_jac_g, Index &nnz_h_lag, TNLP::IndexStyleEnum &index_style) throw ()
virtual bool get_bounds_info (Index n, Number *x_l, Number *x_u, Index m, Number *g_l, Number *g_u) throw ()
virtual bool get_scaling_parameters (Number &, bool &use_x_scaling, Index n, Number *x_scaling, bool &use_g_scaling, Index m, Number *g_scaling) throw ()
virtual bool get_variables_linearity (Index n, LinearityType *var_types) throw ()
virtual bool get_function_linearity (Index m, LinearityType *const_types) throw ()
virtual bool get_starting_point (Index n, bool init_x, Number *x, bool init_z, Number *z_L, Number *z_U, Index m, bool init_lambda, Number *) throw ()
virtual bool get_warm_start_iterate (Ipopt::IteratesVector &) throw ()
virtual bool eval_f (Index n, const Number *x, bool new_x, Number &obj_value) throw ()
virtual bool eval_grad_f (Index n, const Number *x, bool new_x, Number *grad_f) throw ()
virtual bool eval_g (Index n, const Number *x, bool new_x, Index m, Number *g) throw ()
virtual bool eval_jac_g (Index n, const Number *x, bool new_x, Index m, Index, Index *iRow, Index *jCol, Number *values) throw ()
virtual bool eval_h (Index n, const Number *x, bool, Number obj_factor, Index m, const Number *lambda, bool, Index nele_hess, Index *iRow, Index *jCol, Number *values) throw ()
virtual void finalize_solution (Ipopt::SolverReturn status, Index n, const Number *x, const Number *, const Number *, Index m, const Number *g, const Number *lambda, Number obj_value, const Ipopt::IpoptData *, Ipopt::IpoptCalculatedQuantities *) throw ()
virtual bool intermediate_callback (Ipopt::AlgorithmMode, Index, Number, Number, Number, Number, Number, Number, Number, Number, Index, const Ipopt::IpoptData *, Ipopt::IpoptCalculatedQuantities *) throw ()
virtual Index get_number_of_nonlinear_variables () throw ()
virtual bool get_list_of_nonlinear_variables (Index, Index *) throw ()
template<>
bool get_nlp_info (Index &n, Index &m, Index &nnz_jac_g, Index &nnz_h_lag, TNLP::IndexStyleEnum &index_style) throw()
template<>
bool eval_jac_g (Index n, const Number *x, bool, Index ROBOPTIM_DEBUG_ONLY(m), Index nele_jac, Index *iRow, Index *jCol, Number *values) throw()
template<>
bool get_nlp_info (Index &n, Index &m, Index &nnz_jac_g, Index &nnz_h_lag, TNLP::IndexStyleEnum &index_style) throw()
template<>
bool eval_jac_g (Index n, const Number *x, bool, Index m, Index nele_jac, Index *iRow, Index *jCol, Number *values) throw()
template<>
bool eval_h (Index n, const Number *x, bool, Number obj_factor, Index ROBOPTIM_DEBUG_ONLY(m), const Number *lambda, bool, Index ROBOPTIM_DEBUG_ONLY(nele_hess), Index *iRow, Index *jCol, Number *values) throw()
Protected Member Functions
void compute_hessian (TwiceDifferentiableFunction::hessian_t &h, const typename solver_t::vector_t &x, Number obj_factor, const Number *lambda) throw ()
template<>
void compute_hessian (TwiceDifferentiableFunction::hessian_t &h, const typename solver_t::vector_t &x, Number obj_factor, const Number *lambda) throw()
Static Protected Attributes
static log4cxx::LoggerPtr logger
Pointer to function logger (see log4cxx documentation).
Member Typedef Documentation
template<typename T > typedef T roboptim::detail::Tnlp< T >::solver_t
Constructor & Destructor Documentation
template<typename T > roboptim::detail::Tnlp< T >::Tnlp (const typename solver_t::problem_t & pb, solver_t & solver) throw ()
Member Function Documentation
template<typename T > void roboptim::detail::Tnlp< T >::compute_hessian (TwiceDifferentiableFunction::hessian_t & h, const typename solver_t::vector_t & x, Number obj_factor, const Number * lambda) throw () protected
template<> void roboptim::detail::Tnlp< IpoptSolverTd >::compute_hessian (TwiceDifferentiableFunction::hessian_t & h, const typename solver_t::vector_t & x, Number obj_factor, const Number * lambda) throw() inline protected
template<typename T > Function::size_type roboptim::detail::Tnlp< T >::constraintsOutputSize ()
References roboptim::detail::computeConstraintsOutputSize().
template<typename T > bool roboptim::detail::Tnlp< T >::eval_f (Index n, const Number * x, bool new_x, Number & obj_value) throw () virtual
template<typename T > bool roboptim::detail::Tnlp< T >::eval_g (Index n, const Number * x, bool new_x, Index m, Number * g) throw () virtual
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
template<typename T > bool roboptim::detail::Tnlp< T >::eval_grad_f (Index n, const Number * x, bool new_x, Number * grad_f) throw () virtual
References roboptim::detail::IpoptCheckGradient().
template<typename T > bool roboptim::detail::Tnlp< T >::eval_h (Index n, const Number * x, bool , Number obj_factor, Index m, const Number * lambda, bool , Index nele_hess, Index * iRow, Index * jCol, Number * values) throw () virtual
template<> bool roboptim::detail::Tnlp< IpoptSolverTd >::eval_h (Index n, const Number * x, bool , Number obj_factor, Index ROBOPTIM_DEBUG_ONLYm, const Number * lambda, bool , Index ROBOPTIM_DEBUG_ONLYnele_hess, Index * iRow, Index * jCol, Number * values) throw() inline
template<> bool roboptim::detail::Tnlp< IpoptSolverSparse >::eval_jac_g (Index n, const Number * x, bool , Index ROBOPTIM_DEBUG_ONLYm, Index nele_jac, Index * iRow, Index * jCol, Number * values) throw()
References roboptim::detail::IpoptCheckGradient().
template<typename T > bool roboptim::detail::Tnlp< T >::eval_jac_g (Index n, const Number * x, bool new_x, Index m, Index , Index * iRow, Index * jCol, Number * values) throw () virtual
References roboptim::detail::IpoptCheckGradient().
template<> bool roboptim::detail::Tnlp< IpoptSolverSparse >::eval_jac_g (Index n, const Number * x, bool , Index m, Index nele_jac, Index * iRow, Index * jCol, Number * values) throw()
template<typename T > void roboptim::detail::Tnlp< T >::finalize_solution (Ipopt::SolverReturn status, Index n, const Number * x, const Number * , const Number * , Index m, const Number * g, const Number * lambda, Number obj_value, const Ipopt::IpoptData * , Ipopt::IpoptCalculatedQuantities *) throw () virtual
References FILL_RESULT, MAP_IPOPT_ERRORS, MAP_IPOPT_FATALS, SWITCH_ERROR, and SWITCH_FATAL.
template<typename T > bool roboptim::detail::Tnlp< T >::get_bounds_info (Index n, Number * x_l, Number * x_u, Index m, Number * g_l, Number * g_u) throw () virtual
template<typename T > bool roboptim::detail::Tnlp< T >::get_function_linearity (Index m, LinearityType * const_types) throw () virtual
template<typename T > bool roboptim::detail::Tnlp< T >::get_list_of_nonlinear_variables (Index , Index *) throw () virtual
template<> bool roboptim::detail::Tnlp< IpoptSolverSparse >::get_nlp_info (Index & n, Index & m, Index & nnz_jac_g, Index & nnz_h_lag, TNLP::IndexStyleEnum & index_style) throw()
template<typename T > bool roboptim::detail::Tnlp< T >::get_nlp_info (Index & n, Index & m, Index & nnz_jac_g, Index & nnz_h_lag, TNLP::IndexStyleEnum & index_style) throw () virtual
template<> bool roboptim::detail::Tnlp< IpoptSolverSparse >::get_nlp_info (Index & n, Index & m, Index & nnz_jac_g, Index & nnz_h_lag, TNLP::IndexStyleEnum & index_style) throw()
template<typename T > Index roboptim::detail::Tnlp< T >::get_number_of_nonlinear_variables () throw () virtual
template<typename T > bool roboptim::detail::Tnlp< T >::get_scaling_parameters (Number & , bool & use_x_scaling, Index n, Number * x_scaling, bool & use_g_scaling, Index m, Number * g_scaling) throw () virtual
template<typename T > bool roboptim::detail::Tnlp< T >::get_starting_point (Index n, bool init_x, Number * x, bool init_z, Number * z_L, Number * z_U, Index m, bool init_lambda, Number *) throw () virtual
template<typename T > bool roboptim::detail::Tnlp< T >::get_variables_linearity (Index n, LinearityType * var_types) throw () virtual
template<typename T > bool roboptim::detail::Tnlp< T >::get_warm_start_iterate (Ipopt::IteratesVector &) throw () virtual
template<typename T > bool roboptim::detail::Tnlp< T >::intermediate_callback (Ipopt::AlgorithmMode , Index , Number , Number , Number , Number , Number , Number , Number , Number , Index , const Ipopt::IpoptData * , Ipopt::IpoptCalculatedQuantities *) throw () virtual
Member Data Documentation
template<typename T > log4cxx::LoggerPtr roboptim::detail::Tnlp< T >::logger static protected
Pointer to function logger (see log4cxx documentation).