roboptim::detail Namespace Reference
roboptim::detail Namespace Reference
Classes
class Tnlp
Typedefs
typedef Ipopt::Index Index
typedef Ipopt::Number Number
Functions
template<typename T , typename F >
void IpoptCheckGradient (const F &, unsigned, const Eigen::Map< const Function::vector_t > &, int, T &)
template<typename T >
void fillMultipliers (Function::vector_t &multipliers, const Function::value_type *z_L, const Function::value_type *z_U, const Function::value_type *lambda, Function::size_type n, Function::size_type m, const Solver< T > &solver)
ROBOPTIM_CORE_IPOPT_PLUGIN_CHECK_GRADIENT.
void jacobianFromGradients (DerivableFunction::matrix_t &jac, const IpoptSolver::problem_t::constraints_t &c, const DerivableFunction::vector_t &x)
template<typename T >
Tnlp< T >::size_type computeConstraintsOutputSize (const T &solver)
Typedef Documentation
typedef Ipopt::Index roboptim::detail::Index
typedef Ipopt::Number roboptim::detail::Number
Function Documentation
template<typename T > Tnlp<T>::size_type roboptim::detail::computeConstraintsOutputSize (const T & solver)
Referenced by roboptim::detail::Tnlp< T >::constraintsOutputSize().
template<typename T > void roboptim::detail::fillMultipliers (Function::vector_t & multipliers, const Function::value_type * z_L, const Function::value_type * z_U, const Function::value_type * lambda, Function::size_type n, Function::size_type m, const Solver< T > & solver)
ROBOPTIM_CORE_IPOPT_PLUGIN_CHECK_GRADIENT.
template<typename T , typename F > void roboptim::detail::IpoptCheckGradient (const F & , unsigned , const Eigen::Map< const Function::vector_t > & , int , T &)
Referenced by roboptim::detail::Tnlp< T >::eval_grad_f(), and roboptim::detail::Tnlp< T >::eval_jac_g().
void roboptim::detail::jacobianFromGradients (DerivableFunction::matrix_t & jac, const IpoptSolver::problem_t::constraints_t & c, const DerivableFunction::vector_t & x)